server:
  port: 8080
  tomcat:
    connection-timeout: 5s
    relaxed-query-chars: |

hygieia:
  request-dispatch:
    url: unset
  admin-key: unset
  internal:
    client-keys: unset

spring:
  config:
    import:
      - open-api-configuration.yaml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false
    livenessState:
      enabled: true
    readinessState:
      enabled: true

#
# The RestTemplate configuration inherited from Service Start will
# assume mTLS as a default and want keystore and trust store details.
# We do not need mTLS.
#
ssl:
  enable-client: false
  use-trust-store: false

encryption-service:
  key: unset

#
# The following removes some stack trace spam from the log files to make
# them easier to read
#
logging:
  pattern:
    console: >-
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint}
      %clr(%5p)
      %clr(${PID: }){magenta}
      %clr(---){faint}
      %clr([%15.15t]){faint}
      %clr(%-40.40logger{39}){cyan}
      %clr(:){faint}
      %m%n%wEx{full,${logging.stack-trace-filter}}}"
  stack-trace-filter: >-
    ByCGLIB,
    io.netty,
    jakarta.servlet.http,
    java.base,
    java.lang.reflect.Method,
    net.sf.cglib,
    org.apache.catalina,
    org.apache.coyote,
    org.apache.tomcat,
    org.springframework.aop,
    org.springframework.boot.actuate,
    org.springframework.cglib,
    org.springframework.security,
    org.springframework.transaction,
    org.springframework.validation.beanvalidation,
    org.springframework.web,
    reactor.core,
    reactor.ipc,
    sun.reflect

